using System.Collections.Generic;
using OkonkwoETrade10.Order;

namespace OkonkwoETrade10.REST.OrderRequest
{
   public class PlaceOrderRequest : Request, IOrderRequest
   {
      /// <summary>
      /// The type of order being placed
      /// </summary>
      public string orderType { get; set; }

      /// <summary>
      /// A reference number generated by the developer used to ensure that a duplicate order is not being submitted. 
      /// This ID may be any value of 20 or less alphanumeric characters, but it must be unique within this account. 
      /// This field does not appear in any API responses.	
      /// </summary>
      public string clientOrderId { get; set; }

      /// <summary>
      /// The details of the order	
      /// </summary>
      public List<OrderDetail> order { get; set; }

      /// <summary>
      /// This parameter is required and must specify the numeric preview ID from the preview and the other parameters of this request must match the parameters of the preview.
      /// </summary>
      public List<PreviewId> previewIds { get; set; }
   }
}
