using OkonkwoETrade10.REST;

namespace OkonkwoETrade10.Order.REST.OrderRequest
{
   public class PreviewOrderRequest : Request
   {
      /// <summary>
      /// The type of order being placed
      /// </summary>
      public string orderType { get; set; }

      /// <summary>
      /// The order details for the preview order request
      /// </summary>
      public OrderDetail order { get; set; }

      /// <summary>
      /// A reference number generated by the developer used to ensure that a duplicate order is not being submitted. 
      /// This ID may be any value of 20 or less alphanumeric characters, but it must be unique within this account. 
      /// This field does not appear in any API responses.	
      /// </summary>
      public string clientOrderId { get; set; }
   }
}
